<?php
// index.php (Home Page)

// Include common functions and managers for frontend
require_once __DIR__ . '/includes/header.php'; // This includes functions.php and starts session
require_once __DIR__ . '/classes/ProductFrontendManager.php';
require_once __DIR__ . '/classes/CategoryFrontendManager.php';

$productManager = new ProductFrontendManager();
$categoryManager = new CategoryFrontendManager();

// Fetch products for different sections
$bridalProducts = $productManager->getFilteredProducts('bridal', 4); // Get 4 bridal products
$formalProducts = $productManager->getFilteredProducts('formal', 4); // Get 4 formal products
$partywearProducts = $productManager->getFilteredProducts('partywear', 4); // Get 4 partywear products
$trendyProducts = $productManager->getFilteredProducts('trendy', 4); // Get 4 trendy products
$newArrivalsProducts = $productManager->getFilteredProducts('new_arrivals', 4); // Get 4 new arrivals

// Hero slider images (placeholders, you'll upload these to assets/img/)
$heroImages = [
    BASE_URL . 'assets/img/hero1.jpg',
    BASE_URL . 'assets/img/hero2.jpg',
    BASE_URL . 'assets/img/hero3.jpg',
    BASE_URL . 'assets/img/hero4.jpg',
];

?>

<!-- Hero Section (Image Slider) -->
<section class="hero-section">
    <?php foreach ($heroImages as $index => $image): ?>
        <div class="hero-slide <?php echo ($index === 0) ? 'active' : ''; ?>" style="background-image: url('<?php echo $image; ?>');"></div>
    <?php endforeach; ?>
    <div class="hero-overlay">
        <h1>Elegance Redefined.</h1>
        <p>Discover your dream dress for every special occasion.</p>
        <a href="<?php echo BASE_URL; ?>category.php?name=all" class="btn hero-button">Shop Now</a>
    </div>
    <div class="hero-indicators">
        <!-- Indicators will be generated by JavaScript -->
    </div>
</section>

<!-- Category Sections -->
<section class="container-fluid container-xl py-5 category-section">
    <h2 class="text-center mb-5 text-primary-custom">Our Exquisite Collections</h2>

    <!-- Bridal Collection -->
    <h3 class="text-center mb-4 text-dark-custom">Bridal Collection</h3>
    <?php if (!empty($bridalProducts)): ?>
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4 mb-5">
            <?php foreach ($bridalProducts as $product): ?>
                <div class="col">
                    <div class="product-card">
                        <img src="<?php echo BASE_URL . htmlspecialchars($product['image_url']); ?>" class="product-card-img" alt="<?php echo htmlspecialchars($product['name']); ?>" onerror="this.onerror=null;this.src='https://placehold.co/400x300/E0E0E0/555555?text=No+Image';">
                        <div class="product-card-body">
                            <h4><?php echo htmlspecialchars($product['name']); ?></h4>
                            <p class="price">$<?php echo htmlspecialchars(number_format($product['price'], 2)); ?></p>
                            <?php if ($product['is_out_of_stock']): ?>
                                <span class="out-of-stock-badge">Out of Stock</span>
                            <?php else: ?>
                                <a href="<?php echo BASE_URL; ?>product_detail.php?id=<?php echo htmlspecialchars($product['id']); ?>" class="btn btn-details">View Details</a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="text-center mb-5">
            <a href="<?php echo BASE_URL; ?>category.php?name=bridal" class="btn btn-primary-custom hero-button">View All Bridal</a>
        </div>
    <?php else: ?>
        <p class="text-center text-muted-gray mb-5">No bridal products available yet. Please check back later!</p>
    <?php endif; ?>

    <!-- Formal Collection -->
    <h3 class="text-center mb-4 text-dark-custom">Formal Collection</h3>
    <?php if (!empty($formalProducts)): ?>
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4 mb-5">
            <?php foreach ($formalProducts as $product): ?>
                <div class="col">
                    <div class="product-card">
                        <img src="<?php echo BASE_URL . htmlspecialchars($product['image_url']); ?>" class="product-card-img" alt="<?php echo htmlspecialchars($product['name']); ?>" onerror="this.onerror=null;this.src='https://placehold.co/400x300/E0E0E0/555555?text=No+Image';">
                        <div class="product-card-body">
                            <h4><?php echo htmlspecialchars($product['name']); ?></h4>
                            <p class="price">$<?php echo htmlspecialchars(number_format($product['price'], 2)); ?></p>
                            <?php if ($product['is_out_of_stock']): ?>
                                <span class="out-of-stock-badge">Out of Stock</span>
                            <?php else: ?>
                                <a href="<?php echo BASE_URL; ?>product_detail.php?id=<?php echo htmlspecialchars($product['id']); ?>" class="btn btn-details">View Details</a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="text-center mb-5">
            <a href="<?php echo BASE_URL; ?>category.php?name=formal" class="btn btn-primary-custom hero-button">View All Formal</a>
        </div>
    <?php else: ?>
        <p class="text-center text-muted-gray mb-5">No formal products available yet. Please check back later!</p>
    <?php endif; ?>

    <!-- Partywear Collection -->
    <h3 class="text-center mb-4 text-dark-custom">Partywear Collection</h3>
    <?php if (!empty($partywearProducts)): ?>
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4 mb-5">
            <?php foreach ($partywearProducts as $product): ?>
                <div class="col">
                    <div class="product-card">
                        <img src="<?php echo BASE_URL . htmlspecialchars($product['image_url']); ?>" class="product-card-img" alt="<?php echo htmlspecialchars($product['name']); ?>" onerror="this.onerror=null;this.src='https://placehold.co/400x300/E0E0E0/555555?text=No+Image';">
                        <div class="product-card-body">
                            <h4><?php echo htmlspecialchars($product['name']); ?></h4>
                            <p class="price">$<?php echo htmlspecialchars(number_format($product['price'], 2)); ?></p>
                            <?php if ($product['is_out_of_stock']): ?>
                                <span class="out-of-stock-badge">Out of Stock</span>
                            <?php else: ?>
                                <a href="<?php echo BASE_URL; ?>product_detail.php?id=<?php echo htmlspecialchars($product['id']); ?>" class="btn btn-details">View Details</a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="text-center mb-5">
            <a href="<?php echo BASE_URL; ?>category.php?name=partywear" class="btn btn-primary-custom hero-button">View All Partywear</a>
        </div>
    <?php else: ?>
        <p class="text-center text-muted-gray mb-5">No partywear products available yet. Please check back later!</p>
    <?php endif; ?>

    <!-- Trendy Collection -->
    <h3 class="text-center mb-4 text-dark-custom">Trendy Collection</h3>
    <?php if (!empty($trendyProducts)): ?>
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4 mb-5">
            <?php foreach ($trendyProducts as $product): ?>
                <div class="col">
                    <div class="product-card">
                        <img src="<?php echo BASE_URL . htmlspecialchars($product['image_url']); ?>" class="product-card-img" alt="<?php echo htmlspecialchars($product['name']); ?>" onerror="this.onerror=null;this.src='https://placehold.co/400x300/E0E0E0/555555?text=No+Image';">
                        <div class="product-card-body">
                            <h4><?php echo htmlspecialchars($product['name']); ?></h4>
                            <p class="price">$<?php echo htmlspecialchars(number_format($product['price'], 2)); ?></p>
                            <?php if ($product['is_out_of_stock']): ?>
                                <span class="out-of-stock-badge">Out of Stock</span>
                            <?php else: ?>
                                <a href="<?php echo BASE_URL; ?>product_detail.php?id=<?php echo htmlspecialchars($product['id']); ?>" class="btn btn-details">View Details</a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="text-center mb-5">
            <a href="<?php echo BASE_URL; ?>category.php?name=trendy" class="btn btn-primary-custom hero-button">View All Trendy</a>
        </div>
    <?php else: ?>
        <p class="text-center text-muted-gray mb-5">No trendy products available yet. Keep ordering to make some trendy!</p>
    <?php endif; ?>

    <!-- New Arrivals -->
    <h3 class="text-center mb-4 text-dark-custom">New Arrivals</h3>
    <?php if (!empty($newArrivalsProducts)): ?>
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4 mb-5">
            <?php foreach ($newArrivalsProducts as $product): ?>
                <div class="col">
                    <div class="product-card">
                        <img src="<?php echo BASE_URL . htmlspecialchars($product['image_url']); ?>" class="product-card-img" alt="<?php echo htmlspecialchars($product['name']); ?>" onerror="this.onerror=null;this.src='https://placehold.co/400x300/E0E0E0/555555?text=No+Image';">
                        <div class="product-card-body">
                            <h4><?php echo htmlspecialchars($product['name']); ?></h4>
                            <p class="price">$<?php echo htmlspecialchars(number_format($product['price'], 2)); ?></p>
                            <?php if ($product['is_out_of_stock']): ?>
                                <span class="out-of-stock-badge">Out of Stock</span>
                            <?php else: ?>
                                <a href="<?php echo BASE_URL; ?>product_detail.php?id=<?php echo htmlspecialchars($product['id']); ?>" class="btn btn-details">View Details</a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="text-center mb-5">
            <a href="<?php echo BASE_URL; ?>category.php?name=new_arrivals" class="btn btn-primary-custom hero-button">View All New Arrivals</a>
        </div>
    <?php else: ?>
        <p class="text-center text-muted-gray mb-5">No new arrival products from the last 30 days. Stay tuned for updates!</p>
    <?php endif; ?>

</section>

<!-- Shop Now Call to Action -->
<section class="shop-now-section">
    <div class="container-fluid container-xl">
        <h2>Ready to Find Your Perfect Outfit?</h2>
        <a href="<?php echo BASE_URL; ?>category.php?name=all" class="btn shop-now-button">Shop All Dresses</a>
    </div>
</section>

<?php
require_once __DIR__ . '/includes/footer.php';
?>
